package com.bilkent.subfly.getout;

import android.content.Intent;
import android.os.StrictMode;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import Model.User;
import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class SignUpActivity extends AppCompatActivity {

    private static final String TAG = "SignUpActivity";

    private Button sendMail;
    private EditText newMail;
    private EditText password;
    private TextView passwordText;
    private EditText password2;
    private TextView passwordText2;
    private FirebaseAuth mAuth;
    private FirebaseAuth.AuthStateListener mAuthListener;
    private String autoGeneratedPassword;
    private FirebaseDatabase database;
    private DatabaseReference userReference;
    private TextView verificationText;
    private EditText verificationCode;
    private TextView informText;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        /**
         * Added by Tolga 21.12.2018
         */
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);
        //
        super.onCreate(savedInstanceState);
        setContentView(R.layout.sign_up_layout);

        sendMail = findViewById(R.id.sendCodeID);
        newMail = findViewById(R.id.emailEdit2ID);
        /**
         * Added by Tolga 21.12.2018
         */
        verificationCode = findViewById(R.id.verificationCode);
        verificationText = findViewById(R.id.verificationText);
        informText = findViewById(R.id.informText);
        password = findViewById(R.id.passwordEdit2ID);
        passwordText = findViewById(R.id.password);
        password2 = findViewById(R.id.passwordEdit2ID2);
        passwordText2 = findViewById(R.id.password2);
        password.setVisibility( View.INVISIBLE);
        passwordText.setVisibility( View.INVISIBLE);
        password2.setVisibility( View.INVISIBLE);
        passwordText2.setVisibility( View.INVISIBLE);
        informText.setVisibility(View.INVISIBLE);
        verificationText.setVisibility(View.INVISIBLE);
        verificationCode.setVisibility(View.INVISIBLE);

        //
        database = FirebaseDatabase.getInstance();
        mAuth = FirebaseAuth.getInstance();
        userReference = database.getReference("users");

        //Firebase Communication
        userReference.child("users").addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                String value = dataSnapshot.getValue(String.class);
                //Toast.makeText(getApplication(), value, Toast.LENGTH_LONG).show();
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {
                //Do nothing...
            }
        });

        mAuthListener = new FirebaseAuth.AuthStateListener() {
            @Override
            public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                FirebaseUser user = firebaseAuth.getCurrentUser();
                if (user != null) {
                    Log.d(TAG, "user signed in");
                } else
                    Log.d(TAG, "user signed out");
            }
        };

        sendMail.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final String gatheredMail = newMail.getText().toString();
                String bilkentMail = "@ug.bilkent.edu.tr";
                boolean doesContain = false;
                // Check whether the mail that was entered is bilkentMail or not
                for (int i = 0; i <= gatheredMail.length() - bilkentMail.length(); i++) {
                    if (gatheredMail.substring(i, i + bilkentMail.length()).equals(bilkentMail)) {
                        doesContain = true;
                    }
                }
                // If a bilkentMail is entered
                if (doesContain) {
                    autoGeneratedPassword = "";
                    // Generate a password
                    for (int i = 0; i < 6; i++) {
                        int random = (int) (Math.random() * 26) + 65;
                        autoGeneratedPassword += (char) random;
                    }
                    System.out.println(autoGeneratedPassword);
                    try{
                        OkHttpClient client = new OkHttpClient();
                        /**
                         * Updated by Tolga at 21.12.2018
                         */
                        RequestBody postData = new FormBody.Builder().add("email", newMail.getText().toString()).add("generated_password", autoGeneratedPassword).build();
                        //
                        Request request = new Request.Builder().url("https://get-out-mail-sender.000webhostapp.com/index.php").post(postData).build();
                        Response response = client.newCall(request).execute();
                        String result = response.body().string();
                        System.out.println("Sent");
                    }catch (Exception e){
                        System.out.println("Not sent");
                        e.printStackTrace();
                    }
                    /**
                     * Added by Tolga 21.12.2018
                     **/
                    sendMail.setText( "Verify");
                    verificationCode.setVisibility( View.VISIBLE);
                    verificationText.setVisibility( View.VISIBLE);
                    informText.setVisibility(View.VISIBLE);
                    sendMail.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            if (verificationCode.getText().toString().equals(autoGeneratedPassword)) {

                                verificationCode.setVisibility( View.INVISIBLE);
                                verificationText.setVisibility( View.INVISIBLE);
                                informText.setVisibility(View.INVISIBLE);
                                password.setVisibility(View.VISIBLE);
                                passwordText.setVisibility(View.VISIBLE);
                                password2.setVisibility(View.VISIBLE);
                                passwordText2.setVisibility(View.VISIBLE);
                                sendMail.setText( "Sign up");
                                sendMail.setOnClickListener(new View.OnClickListener() {
                                    @Override
                                    public void onClick(View view) {
                                        if( password.getText().toString().equals( password2.getText().toString()))
                                        {
                                            if(password.getText().toString().length() < 6 ){
                                                Toast.makeText(getApplicationContext(), "Password must be at least 6 characters!", Toast.LENGTH_LONG).show();
                                            }else{
                                                mAuth.createUserWithEmailAndPassword(gatheredMail, password.getText().toString())
                                                        .addOnCompleteListener(SignUpActivity.this, new OnCompleteListener<AuthResult>() {
                                                            @Override
                                                            public void onComplete(@NonNull Task<AuthResult> task) {
                                                                if (task.isSuccessful()) {
                                                                    Log.d(TAG, "The User is created");
                                                                    FirebaseUser user = mAuth.getCurrentUser();
                                                                    // Add user to the database
                                                                    User newUser = new User(newMail.getText().toString(), password.getText().toString());
                                                                    userReference.child(newUser.getName()).setValue(newUser);
                                                                    userReference.child(newUser.getName()).child("password").setValue(password.getText().toString());
                                                                    Intent intent = new Intent(getApplication(), LoginActivity.class);
                                                                    startActivity(intent);
                                                                } else {
                                                                    Log.w(TAG, "The User could not created.", task.getException());
                                                                    Toast.makeText(SignUpActivity.this, "Authentication failed", Toast.LENGTH_SHORT).show();
                                                                }
                                                            }
                                                        });
                                            }
                                        }
                                        else
                                            Toast.makeText(SignUpActivity.this, "The passwords does not match!", Toast.LENGTH_LONG).show();
                                    }
                                });

                            } else {
                                Toast.makeText(SignUpActivity.this, "You have entered wrong verification code.", Toast.LENGTH_SHORT).show();
                            }
                            //
                        }
                    });
                }
                else
                {
                    Toast.makeText(getApplication(), "E-Mail is not a Bilkent Mail!!!", Toast.LENGTH_LONG).show();
                }
            }
        });
    }

    @Override
    protected void onStart() {
        super.onStart();
        mAuth.addAuthStateListener(mAuthListener);
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (mAuthListener != null) {
            mAuth.removeAuthStateListener(mAuthListener);
        }
    }
}
